# Generated by Django 5.1.6 on 2025-02-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('clerk', 'Pricing Clerk'), ('supervisor', 'Supervisor')], default='clerk', max_length=20),
        ),
    ]
