# Generated by Django 5.1.6 on 2025-02-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20250225_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate_per_bale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.IntegerField(default=0),
        ),
    ]
