# Generated by Django 5.1.6 on 2025-02-26 03:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='bale_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inventory',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
