# Generated by Django 5.1.6 on 2025-02-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventory_bale_number_inventory_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='qty_in_stock',
            new_name='quantities',
        ),
        migrations.AddField(
            model_name='inventory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
