# Generated by Django 5.1.6 on 2025-02-26 06:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_qty_in_stock_inventory_quantities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='total_price',
            new_name='cash_sales',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='sold_by',
            new_name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='qty_sold',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='sold_at',
        ),
        migrations.AddField(
            model_name='sales',
            name='assistant_supervisor',
            field=models.CharField(default='Unknown Supervisor', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='cashier',
            field=models.CharField(default='Unknown Cashier', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='date_recorded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sales',
            name='eftpos_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='overing_down',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='till_number',
            field=models.CharField(default='Unknown Till', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='time_recorded',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='z_reading',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
            preserve_default=False,
        ),
    ]
