# Generated by Django 5.1.6 on 2025-02-26 08:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rename_total_price_sales_cash_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='time_recorded',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
