# Generated by Django 5.1.6 on 2025-02-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_sales_cash_sales_alter_sales_eftpos_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='overing_down',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='time_recorded',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
