# Generated by Django 5.1.6 on 2025-02-27 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_inventory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name_plural': 'Sales'},
        ),
    ]
