# Generated by Django 5.1.6 on 2025-02-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_sales_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='down',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cash down after balancing', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='overing',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Excess money after balancing', max_digits=10, null=True),
        ),
    ]
