# Generated by Django 5.1.6 on 2025-02-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_sales_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={},
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
