# Generated by Django 5.1.6 on 2025-03-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_sales_options_alter_shop_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['-date_recorded']},
        ),
        migrations.AlterField(
            model_name='sales',
            name='assistant_supervisor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='cashier',
            field=models.CharField(max_length=255),
        ),
    ]
